name: MiniGameUI
main: miniGameUi\MiniGameUi
version: 1.0.0
api: [4.0.0]
author: djdisodo
description: join minigame using custom ui
depends: FormAPI
website: https://github.com/MiniGameAPI-PM
commands:
  mg:
    description: "open minigame ui"
    permission: minigameui.command
    usage: /mg
permissions:
 minigameui.command:
  default: true
